---
packages_homebrew:
# for Mac App Store
  - mas
# Development - Terminal
  - jq
  - zsh
  - zsh-completions
  - zsh-syntax-highlighting
  - zsh-autosuggestions
# Development - Languages
  - php
  - python
  - python@3.9

packages_homebrew_cask:
  - homebrew/cask-versions/adoptopenjdk8
# Productivity
  - macpass
  - diskwave
  - yed
  - shuttle
  - ha-menu
  - monitorcontrol
# Browsers
  - google-chrome
  - google-chrome-canary
# Common Apps
  - dropbox
  - gimp
  - scribus
  - microsoft-office
  - spotify
  - the-unarchiver
  - istumbler
# Common Apps - Social
  - keybase
  - whatsapp
# Common Apps - Photos
  - exifrenamer
# Common Apps - Videos
  - vlc
  - handbrake
# Development - Terminal
  - iterm2
  - go2shell
# Development - Text Editors/IDEs
  - vscodium
# Development - Cloud storage and related
  - jdownloader
# Development - VPN
  - tunnelblick
  - ssh-tunnel-manager

packages_mac_app_store:
# Productivity
  - name: Amphetamine
    id: 937984704
  - name: Magnet
    id: 441258766
  - name: OTP Manager
    id: 928941247
  - name: AS Timer
    id: 512464723
  - name: Telephone
    id: 406825478
# Development - Text Editors/IDEs
  - name: BBEdit
    id: 404009241
